### ISSUE TITLE
x-uuencode encoding type not handled in 0.9.2

### ISSUE THREAD

**Issue by flok99** [kisli/vmime#101]
Normally they're called "uuencode" but apparently "x-uuencode" is also still used for that. 

diff -uNrBbd vmime.org/src/utility/encoder/encoderFactory.cpp vmime/src/utility/encoder/encoderFactory.cpp
--- vmime.org/src/utility/encoder/encoderFactory.cpp	2012-03-16 12:43:54.000000000 +0100
+++ vmime/src/utility/encoder/encoderFactory.cpp	2015-01-27 13:36:19.418264499 +0100
@@ -43,6 +43,7 @@
 	registerName <b64Encoder>("base64");
 	registerName <qpEncoder>("quoted-printable");
 	registerName <uuEncoder>("uuencode");
+	registerName <uuEncoder>("x-uuencode");
 	registerName <sevenBitEncoder>("7bit");
 	registerName <eightBitEncoder>("8bit");
 	registerName <binaryEncoder>("binary");

**Comment by vincent-richard** [comment]
Fixed, thanks!
