### ISSUE TITLE
sequential words with same encoding but individually invalid

### ISSUE THREAD

**Issue by srepmub** [kisli/vmime#103]
another issue found in the wild: for the following subject line, the base64 padding is now correct, but the words cannot be individually decoded, only together.

Subject: =?utf-8?B?5Lit6Yu85qmf5qKw6JGj5LqL5pyDMTAz5bm056ysMDXlsYbn?=
 =?utf-8?B?rKwwN+asoeitsOeoiw==?=

the following patch solves this, but I can imagine this is not the prettiest solution (for example, I was unable so far to reuse word->getConvertedText). what do you think..?

    --- text.cpp    2012-03-16 12:43:56.000000000 +0100
    +++ /home/srepmub/text.cpp      2015-02-06 16:04:59.934388397 +0100
    @@ -145,9 +145,23 @@
     const string text::getConvertedText(const charset& dest) const
     {
        string out;
    -
    -       for (std::vector <ref <word> >::const_iterator i = m_words.begin() ; i != m_words.end() ; ++i)
    -               out += (*i)->getConvertedText(dest);
    +       string out2;
    +        string buffer;
    +       for (std::vector <ref <word> >::const_iterator i = m_words.begin() ; i != m_words.end() ; ++i) {
    +                buffer = (*i)->getBuffer();
    +               while((i+1) != m_words.end() && (*(i+1))->m_charset == (*i)->m_charset) {
    +                       buffer += (*(i+1))->getBuffer();
    +                       ++i;
    +                }
    +               try {
    +                       charset::convert(buffer, out2, (*i)->m_charset, dest);
    +               }
    +               catch (vmime::exceptions::charset_conv_error& e)
    +               {
    +                       out2 = buffer;
    +                }
    +               out += out2;
    +        }
 
            return (out);
     }

**Comment by vincent-richard** [comment]
Hi!

It seems no exception is thrown when decoding the words:

	vmime::text outText;

	vmime::text::decodeAndUnfold
		("=?utf-8?B?5Lit6Yu85qmf5qKw6JGj5LqL5pyDMTAz5bm056ysMDXlsYbn?="
		 "=?utf-8?B?rKwwN+asoeitsOeoiw==?=", &outText);

	outText.getConvertedText(vmime::charset("utf-8"));

The decoded text is "中鋼機械董事會103年第05屆第07次議程", but I can't read it, so can't be sure. :) So, how do you detect there is a problem when decoding?

I think there are missing some functions in "charsetConverter" to verify the validity of a string in a specific charset (current implementation for iconv, ICU and Windows silently replace invalid sequences with '?').

Thanks,

Vincent

**Comment by srepmub** [comment]
in our version of vmime, word::getConvertedText does not contain this check:

    if (dest == m_charset)
        return m_buffer;  

so because we are converting here from utf-8 to utf-8, the problem does not occur.  disabling the check, or converting to another charset shows the problem, as the individual words are not correctly encoded.

**Comment by srepmub** [comment]
for now, we use the above check, as it fixes the situation for this particular problem, and await your reaction for the more general fix.

**Comment by vincent-richard** [comment]
Fixed, please let me know whether the fix actually works for you!
Thanks.

**Comment by srepmub** [comment]
thanks!! but oof, that's a big patch, and we're still on an old snapshot of vmime..

so my patch was a bit ugly, but suppose we're only interested in getting the converted text of all words together, do you see any problem with my approach..? in other words perhaps, do you think there is there a case where two validly encoded words become invalid after concatenation..? :P

**Comment by vincent-richard** [comment]
Hi!

There should be no problem with your approach (the result is the same), except that the fix I committed has the advantage to directly fix the parsed tree, so that when you generate the message back, the broken words are actually fixed.

Vincent
