### ISSUE TITLE
vmime Compilation issue on visual studio 13

### ISSUE THREAD

**Issue by appapurapu** [kisli/vmime#105]
Hi Vincent,

I am seeing the below compilation issue on vmime:
##########
Error	3093	error C2664: 'STACK *(v3_ext_method *,void *,STACK *)' : cannot convert argument 1 from 'const X509V3_EXT_METHOD *' to 'v3_ext_method *'	C:\Users\rappapurapu\Desktop\mingleClient\visualStudioProject\mobileclient\fgmsp\external\vmime\src\vmime\security\cert\openssl\X509Certificate_OpenSSL.cpp	412
##########

I think it is issue with const method pointer but function looking for just method pointer. 
So, to fix it at X509Certificate_OpenSSL.CPP line number:422, I have made the below change and it fine compiling. 

STACK_OF(CONF_VALUE)* val = method->i2v(method, extValStr, NULL);
==>
STACK_OF(CONF_VALUE)* val = method->i2v(const_cast<struct v3_ext_method*>(method), extValStr, NULL);

Please update me if this is correct change or do you suggest any other way to handle this compilation error?

Thanks,
RajaA

**Comment by vincent-richard** [comment]
Hi!

Thanks for reporting this. Unfortunately, the const_cast() version does not compile on Linux platforms. :-)

The fix I committed uses a template function to workaround the issue.

Please don't hesitate to reopen if it still does not work!

Vincent

**Comment by appapurapu** [comment]
Hi,

Thanks for the update!

RajaA

**Comment by appapurapu** [comment]
I am trying to compile the fix on windows visual studio 13 and I left with below issues.
Please check your template fix once.
##########
1>D:\ClientDevelopment\MingleClient\src\mobileclient\fgmsp\external\vmime\src\vmime\security\cert\openssl\X509Certificate_OpenSSL.cpp(129): error C2989: 'stack_st_CONF_VALUE' : class template has already been declared as a non-class template
1>          D:\ClientDevelopment\MingleClient\src\mobileclient\fgmsp\external\openssl\include\openssl/conf.h(81) : see declaration of 'stack_st_CONF_VALUE'
1>D:\ClientDevelopment\MingleClient\src\mobileclient\fgmsp\external\vmime\src\vmime\security\cert\openssl\X509Certificate_OpenSSL.cpp(129): error C2143: syntax error : missing ';' before '*'
1>D:\ClientDevelopment\MingleClient\src\mobileclient\fgmsp\external\vmime\src\vmime\security\cert\openssl\X509Certificate_OpenSSL.cpp(128): error C3857: 'stack_st_CONF_VALUE': multiple template parameter lists are not allowed
1>D:\ClientDevelopment\MingleClient\src\mobileclient\fgmsp\external\vmime\src\vmime\security\cert\openssl\X509Certificate_OpenSSL.cpp(129): error C2065: 'M' : undeclared identifier
1>D:\ClientDevelopment\MingleClient\src\mobileclient\fgmsp\external\vmime\src\vmime\security\cert\openssl\X509Certificate_OpenSSL.cpp(129): error C2146: syntax error : missing ')' before identifier 'm'
1>D:\ClientDevelopment\MingleClient\src\mobileclient\fgmsp\external\vmime\src\vmime\security\cert\openssl\X509Certificate_OpenSSL.cpp(129): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>D:\ClientDevelopment\MingleClient\src\mobileclient\fgmsp\external\vmime\src\vmime\security\cert\openssl\X509Certificate_OpenSSL.cpp(129): error C2059: syntax error : ')'
1>D:\ClientDevelopment\MingleClient\src\mobileclient\fgmsp\external\vmime\src\vmime\security\cert\openssl\X509Certificate_OpenSSL.cpp(130): error C2143: syntax error : missing ';' before '{'
1>D:\ClientDevelopment\MingleClient\src\mobileclient\fgmsp\external\vmime\src\vmime\security\cert\openssl\X509Certificate_OpenSSL.cpp(130): error C2447: '{' : missing function header (old-style formal list?)
1>D:\ClientDevelopment\MingleClient\src\mobileclient\fgmsp\external\vmime\src\vmime\security\cert\openssl\X509Certificate_OpenSSL.cpp(421): error C2064: term does not evaluate to a function taking 3 arguments
###################

**Comment by appapurapu** [comment]
Hi Vincent,

Your template fix seems problem when we link the openssl lib (say as C library) as this library has definition for STACK_OF which is non template. Which differs with your template declaration below
as redifinition compilation issue on visual studio 13 environment.

// Workaround for i2v() taking either a const or a non-const 'method' on some platforms
template <typename M>
STACK_OF(CONF_VALUE)* call_i2v(X509V3_EXT_METHOD* m, void* p1, STACK_OF(CONF_VALUE)* p2)
{
	return m->i2v(m, p1, p2);
}

I have fixed it by commenting the teamplate declaration like below 

// Workaround for i2v() taking either a const or a non-const 'method' on some platforms
//template <typename M>
STACK_OF(CONF_VALUE)* call_i2v(X509V3_EXT_METHOD* m, void* p1, STACK_OF(CONF_VALUE)* p2)
{
	return m->i2v(m, p1, p2);
}

Please check once and update us.

Thanks,
RajaA

**Comment by vincent-richard** [comment]
Hi!

Actually, the non-template function does not work under GCC. :-)

So, it seems there is an alternate solution: declare two call_i2v functions, one taking a const, and the other one taking a non-const:

    // Workaround for i2v() taking either a const or a non-const 'method' on some platforms
    STACK_OF(CONF_VALUE)* call_i2v(const X509V3_EXT_METHOD* m, void* p1, STACK_OF(CONF_VALUE)* p2)
    {
    	return m->i2v(m, p1, p2);
    }

    STACK_OF(CONF_VALUE)* call_i2v(X509V3_EXT_METHOD* m, void* p1, STACK_OF(CONF_VALUE)* p2)
    {
    	return m->i2v(m, p1, p2);
    }

Could you test it with your compiler?

Thanks!

Vincent

**Comment by appapurapu** [comment]
Hi Vicent,

As soon as you removed template declaration for call_i2v function,  I think your solution is fine.
I did compiled on visual studio 13 and no issues.
You can go head and merge your changes.
Please understand that I only compiled and not executed.

Thanks,
RajaA
