### ISSUE TITLE
vmime exception flgs were wrong for win iconv functions

### ISSUE THREAD

**Issue by appapurapu** [kisli/vmime#106]
Hi,

The exception illegal_byte_sequence_for_charset is defined for windows but actually it is called as 
illegal_byte_sequence_in_charset from CharsetConverter_win.hpp.

This is creating the string mismatch while compiling for windows and it is same for other OS. It should be corrected.

Thanks,
RajaA

**Comment by vincent-richard** [comment]
Hi!

Just fixed this. For now, I don't have access to a Windows system to test Windows builds, so I rely on VMime users for reporting issues. Thanks!

Vincent
