### ISSUE TITLE
Oauth2 access token support for gmail authorization

### ISSUE THREAD

**Issue by cat-cat** [kisli/vmime#118]
How can I connect to gmail using vmime and Oauth2 access token? Using plain login and password does not give stable connection results. After some time gmail rejects attempts to login using login and password. This is not the case when using Oauth2 access token.

**Comment by vincent-richard** [comment]
Hi!

I have implemented OAuth2 into VMime.
Here is the commit https://github.com/kisli/vmime/commit/7e36a7464578bf8e1eabf5e77e972340882e573a and [some example code to use it](http://www.vmime.org/development/xoauth2-authentication-mechanism-gmail.html).

Please let me know about it!

**Comment by cat-cat** [comment]
Thank you for implementation and example.
