### ISSUE TITLE
Access violation in X509Certificate_OpenSSL::verifyHostName

### ISSUE THREAD

**Issue by ptomasini** [kisli/vmime#124]
I'm using Vmime on windows (porting by Elmue on codeproject).
Linked with openssl 1.0.2d.
Testing again a smtps server (TLS) I encountered an access violation error due to method used to check subjectAltName extension of X509 server certificate. More specific the error is on calling
extValStr = ASN1_item_d2i(NULL, &extVal, ext->value->length, ASN1_ITEM_ptr(method->it));

As stated in http://openssl.6102.n7.nabble.com/Trying-to-get-URI-of-CRL-from-certificate-extension-td10665.html the correct and portable way to get an extension from a certificate is by using X509_get_ext_d2i().

I'm now using this implementation:

	bool verify = false;
	STACK_OF(GENERAL_NAME) *altNames = NULL;
	altNames = static_cast<GENERAL_NAMES*>(X509_get_ext_d2i(m_data->cert, NID_subject_alt_name, NULL, NULL));
    if (altNames == NULL) {
        return false;
    }
    int altNamesNum = sk_GENERAL_NAME_num(altNames);
    // Check each name within the extension
    for (int i=0; i<altNamesNum; i++) {
        const GENERAL_NAME *current_name = sk_GENERAL_NAME_value(altNames, i);

        if (current_name->type == GEN_DNS) {
            // Current name is a DNS name, let's check it
            char *dns_name = (char *) ASN1_STRING_data(current_name->d.dNSName);

            // Make sure there isn't an embedded NUL character in the DNS name
            if (ASN1_STRING_length(current_name->d.dNSName) != strlen(dns_name)) {
                // MalformedCertificate;
                break;
            }
			if (cnMatch(dns_name, hostname.c_str()))
			{
				verify = true;
				break;
			}

            if (s_NoMatch.length())
                s_NoMatch += ", ";

            s_NoMatch += dns_name;
		}

	}

	sk_GENERAL_NAME_pop_free(altNames, GENERAL_NAME_free);
	return verify;

**Comment by vincent-richard** [comment]
Fixed, thanks!
