### ISSUE TITLE
posixSocket::getPeerAddress() is incorrect

### ISSUE THREAD

**Issue by ctpo6** [kisli/vmime#135]
Garbage IP address string is always returned.

Correct version:
string posixSocket::getPeerAddress() const
{
	// Get address of connected peer
	struct sockaddr peer;
	socklen_t peerLen = sizeof(peer);
	if (getpeername(m_desc, reinterpret_cast <sockaddr*>(&peer), &peerLen) != 0) {
		throwSocketError(errno);
	}

	// Convert to numerical presentation format
	char buf[INET6_ADDRSTRLEN];
	if (!inet_ntop(peer.sa_family, &((struct sockaddr_in *)&peer)->sin_addr, buf, sizeof(buf))) {
		throwSocketError(errno);
	}

	return string(buf);
}

Fix is: &((struct sockaddr_in *)&peer)->sin_addr) in inet_ntop() call.
Also 1024 is too much for a string buffer size. Use INET6_ADDRSTRLEN.

**Comment by vincent-richard** [comment]
Fixed, thanks!
