### ISSUE TITLE
Tracer work only on imap protocol 

### ISSUE THREAD

**Issue by 7i77an** [kisli/vmime#137]
Hi Vincent, 

I defined a custom handle tracer.
When use this class with imap, work well, but when use with pop3 or smtp, the pointer to trace class into socket class (m_trace) is null.

I assign the pointer for all protocols equally.

vmime::shared_ptr<vmime::net::store> store = GetStore();
// Enable tracing communication between client and server
store->setTracerFactory(vmime::make_shared  \<myTracerFactory \>());

Thanks for response.

**Comment by vincent-richard** [comment]
Hello!

Just tested the tracer with POP3 using "example6" and found no issue with it. Could you be more precise, please?

Please note that the tracer is always set on the underlying socket, but never on the TLS socket, which may be the issue you have.

**Comment by 7i77an** [comment]
Yes Vincent, my fault.

Thanks.
