### ISSUE TITLE
config.hpp (and 2 other files) are stored in a wrong place while installing

### ISSUE THREAD

**Issue by filippolauria** [kisli/vmime#142]
This is the one liner used to install vMime (all the dependencies are satisfied)
```
# git clone git://github.com/kisli/vmime && mkdir vmime/build && cd vmime/build && \
    cmake ../ -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release && \
    cmake --build . && make install && ldconfig
```
This is some of the output:
```
...
-- Installing: /usr/local/include/vmime/base.hpp
-- Installing: /usr/local/include/vmime/types.hpp
...
-- Installing: /usr/local/include/root/vmime/build/src/vmime/config.hpp
-- Installing: /usr/local/include/root/vmime/build/src/vmime/export-shared.hpp
-- Installing: /usr/local/include/root/vmime/build/src/vmime/export-static.hpp
```
I think that those three last file are stored in the wrong place (for unknown reasons).
If I am right, they should be in:
```
-- Installing: /usr/local/include/vmime/config.hpp
-- Installing: /usr/local/include/vmime/export-shared.hpp
-- Installing: /usr/local/include/vmime/export-static.hpp
```
And actually, when I move them to the, IMHO, right path I can easily build my project. On the other hands, I get the infamous error (at compilation time): `fatal error: vmime/config.hpp: No such file or directory`.

I have tested everything on Ubuntu 12.04 and on Debian 8.

**Comment by vincent-richard** [comment]
Hello, thank your for reporting this.
It should now be fixed with b133ce8cfbef49169ef42143035a7e617b1cc48e.
