### ISSUE TITLE
Critical bug in posixSocket.cpp

### ISSUE THREAD

**Issue by SoulfreezerXP** [kisli/vmime#144]
Hi Vincent,

I think there is a subtle but critical bug in the actual posixSocket.cpp!

Since yesterday I am using the asynchronous resolving of addresses of the posixSocket-class (VMIME_HAVE_GETADDRINFO_A is defined) and suddenly I can observe TEN times more "Error while connecting socket" - exceptions in my logfiles. 

I checked the actual vmime-source-code and the problem seems to be, that if the address-resolving takes MORE than one second (for example 1,4 seconds), an exception is thrown. Thats ok, but the exception has NOT to be thrown, if the resolving is still in the PROGRESS. This can be fixed with an additional check of the EAI_INPROGRESS - Error-Code, which is evaluated by the gai_error-function. 

After this fix here, all seems fine now and all POP3- and IMAP-servers are correctly polled each 2 minutes during the whole day, even if the resolving takes > 1 seconds in rare cases!

Maybe you can check the problem and fix it in the master? 

Helpful links:
http://man7.org/linux/man-pages/man3/getaddrinfo_a.3.html
https://searchcode.com/codesearch/view/18336258/

    --------------------------------------------------
    BUGFIX 
    (Also considers the timeout-handler)
    vmime/platforms/posix/posixSocket.cpp
    --------------------------------------------------
    while (true)
    {
            struct timespec gaiTimeout;
            gaiTimeout.tv_sec = 1;  // query timeout handler every second
            gaiTimeout.tv_nsec = 0;
    
            gaiError = gai_suspend(&gaiRequests, 1, &gaiTimeout);
    
            if (gaiError == 0 || gaiError == EAI_ALLDONE)
            {
                    const int ret = gai_error(&gaiRequest);
    
                    if (ret != 0)
                    {
                            throw vmime::exceptions::connection_error
                                    ("getaddrinfo_a() request failed: " + std::string(gai_strerror(ret)));
                    }
                    else
                    {
                            *addrInfo = gaiRequest.ar_result;
                            break;
                    }
            }
            else if (gaiError != EAI_AGAIN)
            {
                    if (gaiError == EAI_SYSTEM)
                    {
                            const int ret = gai_error(&gaiRequest);  //*** NEW
    
                            if (ret != EAI_INPROGRESS && errno != 0) //*** MODIFIED
                            {
                                    try
                                    {
                                            throwSocketError(errno);
                                    }
                                    catch (exceptions::socket_exception& e)
                                    {
                                            throw vmime::exceptions::connection_error
                                                    ("Error while connecting socket.", e);
                                    }
                            }
                    }
                    else
                    {
                            throw vmime::exceptions::connection_error
                                    ("gai_suspend() failed: " + std::string(gai_strerror(gaiError)));
                    }
            }
    
            // Check for timeout
            if (m_timeoutHandler && m_timeoutHandler->isTimeOut())
            {
                    if (!m_timeoutHandler->handleTimeOut())
                    {
                            throw exceptions::operation_timed_out();
                    }
                    else
                    {
                            // Reset timeout and keep waiting for connection
                            m_timeoutHandler->resetTimeOut();
                    }
            }
    }

**Comment by vincent-richard** [comment]
Hello! Nice find, I have merged your patch into master. Many thanks!
