### ISSUE TITLE
Add knob to turn off "fixBrokenWords"

### ISSUE THREAD

**Issue by jengelh** [kisli/vmime#149]
Consider this bogus To line (it is wrongly marked as gb2312 when it should be gb18030):

```
To: '=?gb2312?B?wdaRY8PA?=' <a.b@c.de>
```

Upto (not including) commit c5c66f9f , `vmime::message::parse()` would finish with a word list similar to this:

```
(gdb) p *words[0]
$165 = (vmime::word &) @0x55555578e208: {<vmime::headerFieldValue> = {<vmime::component> = {<vmime::object> = {
        _vptr.object = 0x7ffff70ef110 <vtable for vmime::word+16>}, m_parsedOffset = 0, 
      m_parsedLength = 1}, <No data fields>}, m_buffer = "'", m_charset = {<vmime::component> = {<vmime::object> = {
        _vptr.object = 0x7ffff70fd030 <vtable for vmime::charset+16>}, m_parsedOffset = 0, m_parsedLength = 0}, 
    m_name = "us-ascii"}, m_lang = ""}
(gdb) p *words[1]
$166 = (vmime::word &) @0x55555578e278: {<vmime::headerFieldValue> = {<vmime::component> = {<vmime::object> = {
        _vptr.object = 0x7ffff70ef110 <vtable for vmime::word+16>}, m_parsedOffset = 1, 
      m_parsedLength = 21}, <No data fields>}, m_buffer = "\xc1\xd6\x91\x63\xc3\xc0", 
  m_charset = {<vmime::component> = {<vmime::object> = {_vptr.object = 0x7ffff70fd030 <vtable for vmime::charset+16>}, 
      m_parsedOffset = 0, m_parsedLength = 0}, m_name = "gb2312"}, m_lang = ""}
(gdb) p *words[2]
$167 = (vmime::word &) @0x55555578dd48: {<vmime::headerFieldValue> = {<vmime::component> = {<vmime::object> = {
        _vptr.object = 0x7ffff70ef110 <vtable for vmime::word+16>}, m_parsedOffset = 22, 
      m_parsedLength = 1}, <No data fields>}, m_buffer = "'", m_charset = {<vmime::component> = {<vmime::object> = {
        _vptr.object = 0x7ffff70fd030 <vtable for vmime::charset+16>}, m_parsedOffset = 0, m_parsedLength = 0}, 
    m_name = "us-ascii"}, m_lang = ""}
```

After parse(), the vmime-using code we have would then go on and fixup the character set and compose a flattened representation with something like:

```
c = myword.getCharset();
if (c == "gb2312")
    c = vmime::charset("gb18030");
else if (c == "iso-8859-8-i")
    c = vmime::charset("iso-8859-8");
return vmime::word(myword, c).getConvertedText(CHARSET_WCHAR);
```

This worked well until commit c5c66f9f where a function `fixBrokenWords` was introduced to vmime, which started replacing the charset if the word did not validate (and indeed, it does not validate as gb2312), turning `words[2]` into:

```
(gdb) p *words[2]
$172 = (vmime::word &) @0x55555578dd48: {<vmime::headerFieldValue> = {<vmime::component> = {<vmime::object> = {
        _vptr.object = 0x7ffff70ef110 <vtable for vmime::word+16>}, m_parsedOffset = 22, 
      m_parsedLength = 1}, <No data fields>}, m_buffer = "\221c\303\300'", 
  m_charset = {<vmime::component> = {<vmime::object> = {_vptr.object = 0x7ffff70fd030 <vtable for vmime::charset+16>}, 
      m_parsedOffset = 0, m_parsedLength = 0}, m_name = "us-ascii"}, m_lang = ""}
```

Because this is now `us-ascii`, there is no way to repair the character set—and subsequently, I get question marks from getConvertedText (since \221 is outside ASCII).

There are more charset names floating around in the Internet that iconv does not know about (like iso-8859-i) but which our software does, and now that would also be broken.

**Comment by vincent-richard** [comment]
Hi!

I ran some tests with your bogus word on my system, and I got 3 words in Test 2, the second one being in charset "gb2312". Here is the source for you to try:

	void testUnknownCharset()
	{
		// Test 1
		vmime::text t;
		vmime::text::decodeAndUnfold("=?gb2312?B?wdaRY8PA?=", &t);

		VASSERT_EQ("1.1", 1, t.getWordCount());
		VASSERT_EQ("1.2", "\xc1\xd6\x91\x63\xc3\xc0", t.getWordAt(0)->getBuffer());
		VASSERT_EQ("1.3", vmime::charset("gb2312"), t.getWordAt(0)->getCharset());

		// Test 2
		vmime::parsingContext ctx;

		const vmime::string hfieldBuffer = "From: '=?gb2312?B?wdaRY8PA?=' <a.b@c.de>";

		vmime::shared_ptr <vmime::headerField> hfield =
			vmime::headerField::parseNext(ctx, hfieldBuffer, 0, hfieldBuffer.size());

		vmime::shared_ptr <vmime::mailbox> hvalue =
			hfield->getValue <vmime::mailbox>();

		VASSERT_EQ("2.1", 3, hvalue->getName().getWordCount());
		VASSERT_EQ("2.2", "'", hvalue->getName().getWordAt(0)->getBuffer());
		VASSERT_EQ("2.3", vmime::charset("us-ascii"), hvalue->getName().getWordAt(0)->getCharset());
		VASSERT_EQ("2.4", "\xc1\xd6\x91\x63\xc3\xc0", hvalue->getName().getWordAt(1)->getBuffer());
		VASSERT_EQ("2.5", vmime::charset("gb2312"), hvalue->getName().getWordAt(1)->getCharset());
		VASSERT_EQ("2.6", "'", hvalue->getName().getWordAt(2)->getBuffer());
		VASSERT_EQ("2.7", vmime::charset("us-ascii"), hvalue->getName().getWordAt(2)->getCharset());
	}

And here is what I got from gdb:

    (gdb) p *hvalue->getName().getWordAt(0)
    $1 = (vmime::word &) @0x670930: {<vmime::headerFieldValue> = {<vmime::component> = {<vmime::object> = {_vptr.object = 0x635c30 <vtable for vmime::word+16>}, m_parsedOffset = 0, 
      m_parsedLength = 1}, <No data fields>}, m_buffer = "'", 
      m_charset = {<vmime::component> = {<vmime::object> = {
            _vptr.object = 0x635ac0 <vtable for vmime::charset+16>}, m_parsedOffset = 0, 
          m_parsedLength = 0}, m_name = "us-ascii"}, m_lang = ""}
    (gdb) p *hvalue->getName().getWordAt(1)
    $2 = (vmime::word &) @0x66ec30: {<vmime::headerFieldValue> = {<vmime::component> = {<vmime::object> = {_vptr.object = 0x635c30 <vtable for vmime::word+16>}, m_parsedOffset = 1, 
          m_parsedLength = 21}, <No data fields>}, m_buffer = "\301֑c\303\300", 
      m_charset = {<vmime::component> = {<vmime::object> = {
            _vptr.object = 0x635ac0 <vtable for vmime::charset+16>}, m_parsedOffset = 0, 
          m_parsedLength = 0}, m_name = "gb2312"}, m_lang = ""}
    (gdb) p *hvalue->getName().getWordAt(2)
    $3 = (vmime::word &) @0x66e600: {<vmime::headerFieldValue> = {<vmime::component> = {<vmime::object> = {_vptr.object = 0x635c30 <vtable for vmime::word+16>}, m_parsedOffset = 22, 
          m_parsedLength = 1}, <No data fields>}, m_buffer = "'", 
      m_charset = {<vmime::component> = {<vmime::object> = {
            _vptr.object = 0x635ac0 <vtable for vmime::charset+16>}, m_parsedOffset = 0, 
          m_parsedLength = 0}, m_name = "us-ascii"}, m_lang = ""}

There might be a bug, but without more context, I can't tell for now! :)

**Comment by jengelh** [comment]
Tried your source and found that you have to build vmime such that it uses `charsetConverter_iconv` rather than `charsetConverter_icu` for it to trigger.

**Comment by jengelh** [comment]
More specifically, ICU considers the subsequence `\x91\x63` to be valid (filed a separate report at https://ssl.icu-project.org/trac/ticket/12843 ), which is why libvmime, when built with icu as converter, considers the vmime::word ok. But if and when a converter chokes, vmime would call fixBrokenWords.

**Comment by vincent-richard** [comment]
Could you please try this [patch](vmime.org/public/download/patches/vmime-20161104-fixbrokenwords.patch)?
I tested it successfully both with ICU and iconv.

**Comment by jengelh** [comment]
Yes, that new patch works up to my expectations.

A slightly odd thing though is that
```
vmime::text::decodeAndUnfold("'=?gb2312?B?wdaRY8PA?==?gb2312?B?wdY=?==?gb2312?B?wdY=?='", &t)
```
now produces a word list with buffer sizes {1,2,8,1} instead of {1,6,2,2,1}.

**Comment by vincent-richard** [comment]
Thank you for testing! As for the output, this is normal, as the new fixBrokenWords() function try to merge as words as possible, instead of only the next one. Hope this is not an issue for you.

**Comment by jengelh** [comment]
Not an issue for this ticket.
