### ISSUE TITLE
Same SONAME for different APIs

### ISSUE THREAD

**Issue by jengelh** [kisli/vmime#155]
Both vmime 0.9.1 and vmime 0.9.2 emit a libvmime.so.0 despite their API having changed. I suggest
```
CMakeLists.txt:SET(VMIME_API_VERSION_CURRENT   1)
```

**Comment by vincent-richard** [comment]
Hello! That's right. Originally, 0.* versions were not intended to be "public", only "pre-release", that's why the API version never changed. However, I totally agree that this should always be updated at each release from now. Fixed with 7627129f4e30064b8fb915fb6339a0aa19a743ca.
