### ISSUE TITLE
Syntactically invalid EHLO argument(s) with cyrillic PC name

### ISSUE THREAD

**Issue by paukonen** [kisli/vmime#160]
Hello!

When computer has cyrillic PC name "Дмитрий-ПК", vmime cannot pass SMTP greeting:

S: [smtp:1]Connecting to smtp.peterhost.ru, port 587
R: [smtp:1]220 smtp.z8.ru ESMTP Exim 4.71 Wed, 08 Feb 2017 12:09:16 +0300
S: [smtp:1]EHLO Ŭ鳰驭Њ
R: [smtp:1]501 Syntactically invalid EHLO argument(s)
S: [smtp:1]HELO Ŭ鳰驭Њ
R: [smtp:1]501 Syntactically invalid HELO argument(s)
S: [smtp:1]Disconnecting

**Comment by vincent-richard** [comment]
Hello, could you please try the following patch and tell me?
http://www.vmime.org/public/download/patches/vmime-20170209-hostname.patch

**Comment by paukonen** [comment]
Hello! Thank you! I've tried your patch, it gives me this error:

src\vmime\platforms\windows\windowsHandler.cpp:214:53: error: 'buffer' was not declared in this scope
   if (GetComputerNameEx((COMPUTER_NAME_FORMAT) cnf, buffer, &hostnameLen))

**Comment by vincent-richard** [comment]
Oops... just replace "buffer" with "hostname".

**Comment by paukonen** [comment]
Thank you, patch is working fine. Now it sends "localhost.localdomain" and authorizes successfully.
