### ISSUE TITLE
"Default encoder" instead of exceptions::no_encoder_available

### ISSUE THREAD

**Issue by paukonen** [kisli/vmime#163]
Hello!

I received lots of emails (mostly spam) that cannot be parsed because of "exceptions::no_encoder_available" exception. These messages probably constructed with mistakes but it would be great to be able to parse them anyway, so it would be possible to identify them as spam and delete them, instead of dealing with exceptions.

I made some changes in my local copy of vmime sources adding conception of "default encoder" in encoderFactory::getEncoderByName() which is used instead of throwing "exceptions::no_encoder_available".
It would be great to have oportunity to set default encoder for such situations through API of vmime. Please consider this.

I'm attaching patch that I'm using.
[patch.txt](https://github.com/kisli/vmime/files/760313/patch.txt)

**Comment by vincent-richard** [comment]
Hello! Fixed this using more flexible `setDefaultEncoder()` and `getDefaultEncoder()` functions.
