### ISSUE TITLE
Bug in dotFilteredInputStream::read method

### ISSUE THREAD

**Issue by LenartSzabolcsCsaba** [kisli/vmime#168]
We found a bug in the method which replaces "\n.." with "\n.". The problem is that only the first occurrence is replaced, because of pointer arithmetic (prevChar2 and prevChar1). 
We also have a fix for the problem, waiting for your reply. 

A test project reproducing this issue is attached. 
[vmime_proj.zip](https://github.com/kisli/vmime/files/872142/vmime_proj.zip)

**Comment by vincent-richard** [comment]
Hello!

Thanks for reporting this, and also for the complete test project.
There was indeed a problem with the `dotFilteredInputStream::read()` function.

Here is a patch that should fix the issue:
http://www.vmime.org/public/download/patches/vmime-20170328-fixdotfilteredis.patch

Please let me know whether it works for you.

**Comment by LenartSzabolcsCsaba** [comment]
Hello!

Thanks for the fast reply and for the patch. 
We tested it for different cases (scenarios that we could think of) and we did not find any error, it looks good.
