### ISSUE TITLE
Install VMIME without boost

### ISSUE THREAD

**Issue by URemery** [kisli/vmime#174]
Hi,

I'm trying to install vmime on my Debian form the git sources. I tried to follow the instructions of the vmime-book and as it's explained i can either use Boost or compile in C++11 (for shared_ptr<>) so I decided to simply compile in C++11. But if I  

> cmake -G "Unix Makefiles" /path...

It tries to find Boost on my computer, impossible bc I do not have Boost, so it stops with an error and I can't follow with 

> cmake --build .

So what should I do to install vmime correctly without Boost ? (from the git sources)

Thanks for your replies

**Comment by anonymous09** [comment]
Hello! Try this:
```
cmake -G "Unix Makefiles" -DVMIME_SHARED_PTR_USE_CXX=ON /path...
```

**Comment by vincent-richard** [comment]
Hello!

VMime should detect automatically whether it can uses C++11 shared_ptr<>. If not, it will fallback on Boost shared_ptr, which leads to the error you get if Boost is not installed.

Are you sure that CMake actually uses the C++11 compiler and pass the correct flags? Could you please copy/paste the output of the "cmake -G ..." command here?
