### ISSUE TITLE
Remove LIB_SUFFIX from CMakeLists.txt

### ISSUE THREAD

**Issue by anonymous09** [kisli/vmime#175]
Hello! I see no reason to keep LIB_SUFFIX in CMakeLists.txt. We have already CMAKE_INSTALL_LIBDIR that should be proper configured.

And now I need patch current CMakeLists.txt for Gentoo Linux, replacing
```
SET(VMIME_INSTALL_LIBDIR ${CMAKE_INSTALL_LIBDIR}${LIB_SUFFIX})
```
with
```
SET(VMIME_INSTALL_LIBDIR ${CMAKE_INSTALL_LIBDIR})
```
and other usages of LIB_SUFFIX.

Maybe just fix upstream? Can I prepare pull request?

**Comment by vincent-richard** [comment]
Hello! Honestly, I don't remember exactly why there was so much code to "detect" installation directory. Maybe there was an issue some time ago. I cleaned the CMakeLists file up and everything seems to work fine on Ubuntu.

**Comment by anonymous09** [comment]
Now it works on Gentoo Linux. Thank you!
