### ISSUE TITLE
Fix build by defining AF_UNSPEC and SOCK_STREAM

### ISSUE THREAD

**Issue by bulibuta** [kisli/vmime#176]
Hi,

posixHandler needs to include sys/socket.h in order to define AF_UNSPEC and SOCK_STREAM on all Unix systems. The attached patch fixes the build at least on OpenBSD systems.

Paul
[patch-src_vmime_platforms_posix_posixHandler_cpp.txt](https://github.com/kisli/vmime/files/1124028/patch-src_vmime_platforms_posix_posixHandler_cpp.txt)

**Comment by vincent-richard** [comment]
Fixed, thanks!
