### ISSUE TITLE
Conversion problem in charsetConverter_Win.cpp

### ISSUE THREAD

**Issue by LenartSzabolcsCsaba** [kisli/vmime#179]
Hello,

I found a bug in charsetConverter_Win.cpp. 
On lines 113 and 146 you calculate the lenght of the buffer:
const size_t bufferSize = in.length() * 2;  // in wide characters
const size_t bufferSize = unicodeLen * 6;  // in multibyte characters

The problem is that on windows this size can be 2 or 4 (in the first case for example). For reference: https://stackoverflow.com/questions/4652519/are-utf16-as-used-by-for-example-wide-winapi-functions-characters-always-2-byt

I think you can replace with this:
const size_t bufferSize = MultiByteToWideChar(sourceCodePage, 0, in.c_str(), static_cast <int>(in.length()), nullptr, 0) * sizeof(WCHAR);  // in wide characters
const size_t bufferSize = WideCharToMultiByte(destCodePage, 0, unicodePtr, static_cast <int>(unicodeLen), nullptr, 0, 0, NULL);  // in multibyte characters

Thanks.

**Comment by vincent-richard** [comment]
Hello!

Thanks for reporting this; you are right, this is the correct way to do it.
