### ISSUE TITLE
Exception: Error while executing command 'MAIL FROM:<xxx@yyy.com> SIZE=xxxx'

### ISSUE THREAD

**Issue by Eggache666** [kisli/vmime#202]
Hello ,

I read some parts of the vmime-book.pdf, and use this library to send mail to smtp server, it throws an exception: 
vmime::exception: Error while executing command 'MAIL FROM:<myname@163.com> SIZE=272211'.
terminate called after throwing an instance of 'vmime::net::smtp::SMTPCommandError'
  what():  Error while executing command 'MAIL FROM:<myname@163.com> SIZE=272211'.
  
//////////////////////////////////////////  
Here is the main code:
The 'msg' is similar to the example3 [https://github.com/kisli/vmime/blob/master/examples/example3.cpp].
// Raw text generation
vmime::string dataToSend = msg->generate();
		
vmime::utility::url url("smtp://smtp.163.com");
vmime::shared_ptr<vmime::net::session> sess = vmime::net::session::create();
vmime::shared_ptr<vmime::net::transport> tr = sess->getTransport(url);

tr->setProperty("options.need−authentication", true);
tr->setProperty("auth.username", "myname);
tr->setProperty("auth.password", auth_code);	// here the 'auth_code' which is a const c-string is not the web login password
tr->connect();

vmime::utility::inputStreamStringAdapter is(dataToSend);
vmime::mailboxList send_to;
send_to.appendMailbox(vmime::make_shared<vmime::mailbox>("someuser@gmail.com"));
vmime::mailbox from("myname@163.com");
tr->send(from, send_to, is, dataToSend.length());	// !!!here throw exception
tr->disconnect();
//////////////////////////////////////////

I don't know how to solve the problem, can someone help me? Thanks!

**Comment by vincent-richard** [comment]
Hello!

Please provide the full client/server exchange, using a [tracer](https://www.vmime.org/development/how-to-use-the-new-logging-facility.html).
Be sure to remove any personal/confidential information!

Vincent

**Comment by vincent-richard** [comment]
Hello!

You are telling VMime you want to authenticate with XOAuth2 and only this, but it seems your SMTP server does not support it.

Just remove the second parameter "xoauth2Auth" to the getTransport() call, and the default authenticator will be used instead (it will use the username and password you set with tr->setProperty(...)).

**Comment by Eggache666** [comment]
Thank you very much!!!
I had a mistake, the code:
tr->setProperty("options.need−authentication", true);
should be:
tr->setProperty("options.need−authentication", **"true"**);
After I removed the "xoauth2Auth", it worked well. 

Although, with those code, the 163 mailbox can send mail, but when I changed smtp server to another,  an error has occurred. Here is the code:
///////////////////////////////////////////////
// first I did not use tls
vmime::shared_ptrvmime::net::session sess = vmime::net::session::create();
vmime::shared_ptrvmime::net::transport tr = sess->getTransport(vmime::utility::url("smtp://smtp.another.com:587"));
tr->setTracerFactory(vmime::make_shared());

tr->setProperty("options.need−authentication", "true");
tr->setProperty("auth.username", "from_me@qq.com");
tr->setProperty("auth.password", auth_code);

the logs:
[smtp:1] C: Connecting to smtp.qq.com, port 587
[smtp:1] S: 220 smtp.qq.com Esmtp QQ Mail Server
[smtp:1] C: EHLO machine
[smtp:1] S: 250-smtp.qq.com
[smtp:1] S: 250-PIPELINING
[smtp:1] S: 250-SIZE 73400320
[smtp:1] S: 250-STARTTLS
[smtp:1] S: 250-AUTH LOGIN PLAIN
[smtp:1] S: 250-AUTH=LOGIN
[smtp:1] S: 250-MAILCOMPRESS
[smtp:1] S: 250 8BITMIME
[smtp:1] C: AUTH LOGIN
[smtp:1] S: 530 Must issue a STARTTLS command first.
[smtp:1] C: Disconnecting
vmime::exception: Authentication error.

Then, I add tls code:
//////////////////////////////////////////////////////////
vmime::shared_ptrvmime::net::session sess = vmime::net::session::create();

vmime::shared_ptrvmime::net::tls::TLSProperties tlsProps = vmime::make_sharedvmime::net::tls::TLSProperties();
tlsProps->setCipherSuite(vmime::net::tls::TLSProperties::CIPHERSUITE_HIGH);
sess->setTLSProperties(tlsProps);

vmime::shared_ptrvmime::net::transport tr = sess->getTransport(vmime::utility::url("smtp://smtp.qq.com:587"));
tr->setTracerFactory(vmime::make_shared());

tr->setProperty("options.need−authentication", "true");
tr->setProperty("auth.username", "from_me@qq.com");
tr->setProperty("auth.password", auth_code);
tr->setProperty("connection.tls", "true");

logs:
[smtp:1] C: Connecting to smtp.qq.com, port 587
[smtp:1] S: 220 smtp.qq.com Esmtp QQ Mail Server
[smtp:1] C: EHLO machine
[smtp:1] S: 250-smtp.qq.com
[smtp:1] S: 250-PIPELINING
[smtp:1] S: 250-SIZE 73400320
[smtp:1] S: 250-STARTTLS
[smtp:1] S: 250-AUTH LOGIN PLAIN
[smtp:1] S: 250-AUTH=LOGIN
[smtp:1] S: 250-MAILCOMPRESS
[smtp:1] S: 250 8BITMIME
[smtp:1] C: STARTTLS
[smtp:1] S: 220 Ready to start TLS
[smtp:1] C: Beginning SSL/TLS handshake
[smtp:1] C: Disconnecting
vmime::exception: error:140740B5:SSL routines:SSL23_CLIENT_HELLO:no ciphers available

Still no success. What's wrong?

By the way, In the page 64 of vmime-book.pdf, I want to use this: tlsProps−>setCipherString("HIGH:!ADH:@`STRENGTH`"); But in the current version of vmime, there is no function 'setCipherString'.

Thank you!

**Comment by Choxmi** [comment]
@Eggache666 I'm facing the same problem. Were you able to find any solution for this?

**Comment by Eggache666** [comment]
@Choxmi Here is an example:

        //............. refer to: https://github.com/kisli/vmime/tree/master/examples
        //
        vmime::string dataToSend = msg->generate();
        std::cout << "Generated message:" << std::endl;
        std::cout << "==================" << std::endl;
        std::cout << std::endl;
        std::cout << dataToSend << std::endl; 

        vmime::utility::url url("smtp://smtp.163.com");
        vmime::shared_ptr<vmime::net::session> sess = vmime::net::session::create();
        vmime::shared_ptr<vmime::net::transport> tr = sess->getTransport(url);
        tr->setProperty("options.need-authentication", "true");
        tr->setProperty("auth.username", "xxxxxx@163.com");
        tr->setProperty("auth.password", "password"); 
        tr->connect();
        //
        //.......  refer to: https://github.com/kisli/vmime/tree/master/examples
        //
        tr->send(msg, from, send_to);
        tr->disconnect();

**Comment by Choxmi** [comment]
Thanks a lot @Eggache666
