### ISSUE TITLE
missing characters in utf8 string

### ISSUE THREAD

**Issue by TomKong666** [kisli/vmime#208]
When using a utf8 characters in a teststring  like "testö string"

```
vmime::shared_ptr <vmime::message>            emsg;
vmime::messageBuilder mb;
...
vmime::charset ch="utf-8";
vmime::text DisplayName;
DisplayName.createFromString(teststring,ch);
mb.setExpeditor(vmime::mailbox(DisplayName,FromAddress));
mb.setSubject(DisplayName);
```

and later diplay the messgage like

```
//show message on stdout
std::cout << "Generated message:" << std::endl;
vmime::utility::outputStreamAdapter out(std::cout);
emsg->generate(out);
std::cout << std::endl;
```

Generated message:
Subject: =?utf-8?Q?test=C3=B6?= string
From: =?utf-8?Q?test=C3=B6?= =?us-ascii?Q?string?= <RealFromName@my.domain>

the space character between "testö " and "string" is missing.

**Comment by vincent-richard** [comment]
Hello!

What makes you say that the space is missing? The space between "...B6?=" and "=?us-ascii..." **IS** significant and should be reincorporated into the text when parsing again. Did you try to parse the message again with VMime or any other (compliant) RFC-2822 parser?

**Comment by TomKong666** [comment]
The subject is displayed correct, the display name part of the from address isn't, at least after sending the mail. I used thunderbird and roundcube as mailbrowser.

**Comment by TomKong666** [comment]
The source code of the mail in my mailbox looks the same as in the generated message:

Subject: =?utf-8?Q?test=C3=B6?= string
From: =?utf-8?Q?test=C3=B6?= =?us-ascii?Q?string?= <RealFromName@c-l.net>

**Comment by TomKong666** [comment]
Source code of the email in my mailbox looks:

Subject: =?utf-8?Q?test=C3=B6?= string
From: =?utf-8?Q?test=C3=B6?= =?us-ascii?Q?string?= <RealFromName@my.domain>
