### ISSUE TITLE
invalid_response when trying to fetch email

### ISSUE THREAD

**Issue by paukonen** [kisli/vmime#213]
Hello!

Receiving exeption on this server response:
[^]* 13 FETCH (BODYSTRUCTURE (("text" "html" ("charset" "cp1251") NIL NIL "base64" 84056 0 NIL ("inline" NIL) NIL NIL)("image" "gif" () "25b2b55b5d97f04e9ea939fe32a46a65.gif" NIL "base64" 20776 NIL ("inline" NIL) NIL NIL) "related" ("boundary" NIL)))

**Comment by vincent-richard** [comment]
Hello!

Please note that this is a non-standard IMAP response.
I have made a patch to add support for this in non-strict mode.
