### ISSUE TITLE
Setting SNI breaks STARTTLS

### ISSUE THREAD

**Issue by RichardSteele** [kisli/vmime#231]
The changes caused by 0fcf45b1317a6e27f613542c6d6cb1511efc134c break upgrading a plain text connection to an encrypted connection!

`TLSSocket_OpenSSL::createSSLHandle` throws an exception if it doesn't know the server's address:
https://github.com/kisli/vmime/blob/19fb3c24916438a46467b7d9270181662fa84ede/src/vmime/net/tls/openssl/TLSSocket_OpenSSL.cpp#L122-L128

The address is made known only in `TLSSocket_OpenSSL::connect`:
https://github.com/kisli/vmime/blob/19fb3c24916438a46467b7d9270181662fa84ede/src/vmime/net/tls/openssl/TLSSocket_OpenSSL.cpp#L181-L186

This function, however, isn't called if you start with a plain connection and upgrade to an encrypted connection via STARTTLS because an existing, already connected socket gets wrapped. I noticed this when using a SMTP connection:
https://github.com/kisli/vmime/blob/19fb3c24916438a46467b7d9270181662fa84ede/src/vmime/net/smtp/SMTPConnection.cpp#L550-L574

**Comment by RichardSteele** [comment]
Using `socket::getPeerName()`` instead of `m_address` might be a solution.

**Comment by vincent-richard** [comment]
Merged, thanks!
