### ISSUE TITLE
OpenSSL license incompatibility

### ISSUE THREAD

**Issue by NiQ1** [kisli/vmime#236]
Hello,
I've noticed that the GPL license does not include the OpenSSL linking exception. Seeing that OpenSSL is officially supported should I assume that's an oversight? Is it permitted to link VMime with OpenSSL in my project and release in both source and binary forms?

Thank you!

**Comment by vincent-richard** [comment]
Haa, license hell... IANAL, but I think that if we add the exception, it will be (legally) impossible to link to other GPLv3 software which do not carry such an exception.

If you have the possibility to use GNUTLS instead of OpenSSL, it would be easier. :-)

**Comment by NiQ1** [comment]
> 
> 
> Haa, license hell... IANAL, but I think that if we add the exception, it will be (legally) impossible to link to other GPLv3 software which do not carry such an exception.
> 
> If you have the possibility to use GNUTLS instead of OpenSSL, it would be easier. :-)

Thank you for your answer.
AFAIK It will not prevent that. Linking to other GPLv3 software without the exception effectively means that the exception is no longer valid for that project (i.e. you won't be allowed to use VMime linked with OpenSSL in that project, which is the case today as well), however the exception will allow using VMime with OpenSSL in GPLv3 projects that also have the same exception.

Anyway, my question is basically whether the VMime project will see it as a copyright violation if I use it with OpenSSL in a GPLv3+exception project and distribute both source and binaries.

**Comment by vincent-richard** [comment]
What I understand is as long as you don't distribute OpenSSL alongside your project (ie. you are linking to it using the libraries installed on the system), it does not matter, but it seems it's not your case.

I am not an expert, so I cannot calmly make the decision to add exceptions to a license without fully understanding its meaning and implications.

Please allow some time so that I grab more infos about this issue, and finally take a decision.

**Comment by vincent-richard** [comment]
OK, se we have finally explicitely included an exception for OpenSSL in VMime license files.

**Comment by NiQ1** [comment]
> 
> 
> OK, se we have finally explicitely included an exception for OpenSSL in VMime license files.

Thank you very much, I really appreciate it! Closing issue.
