### ISSUE TITLE
FROM email and Authenticated email are never the same.

### ISSUE THREAD

**Issue by ADoncel** [kisli/vmime#237]
Trying a simple SMTP email sender test to build a bigger software I get this error every time no matter what I tried:

```
vmime::exceptions::SMTPCommandError
    what = Error while executing command 'DATA'.
    command = DATA
    response = Your FROM address ( x@domain.com ,  ) must match your authenticated
email user ( x@domain.com ).
```

The email accounts are the same, I tried using:
```
tr->setProperty("auth.username", "x@domain.com");
tr->setProperty("auth.password", "xxxxxxxx");
```
as well as:
```
url.setUsername("x@domain.com");
url.setPassword("xxxxxx");
```
And also a lot of ways of building `vmime::mailbox from`, but it seems to have two fields, what doesn't make sense at all.

Thank you for your help.

Best regards
Antonio

**Comment by vincent-richard** [comment]
Hello! Could you please share the full SMTP session log (using a tracer) after removing sensible data from it?

**Comment by ADoncel** [comment]
As I saw in another post, I'm going to try first to build the latest version and come back with results.

**Comment by ADoncel** [comment]
Still the same error, this is the SMTP trace:

`[smtp:1] C: Connecting to mail.domain.com, port 25
[smtp:1] S: 220 vserver80.axc.nl ESMTP Exim 4.92 Fri, 08 May 2020 13:56:55 +0200
[smtp:1] C: EHLO ubuntu-vm-dev
[smtp:1] S: 250-vserver80.axc.nl Hello 166-158-20-31.ftth.glasoperator.nl [31.20.158.166]
[smtp:1] S: 250-SIZE 52428800
[smtp:1] S: 250-8BITMIME
[smtp:1] S: 250-PIPELINING
[smtp:1] S: 250-AUTH PLAIN LOGIN
[smtp:1] S: 250-STARTTLS
[smtp:1] S: 250 HELP
[smtp:1] C: AUTH PLAIN
[smtp:1] S: 334 
[smtp:1] C: {...SASL exchange: 40 bytes of data...}
[smtp:1] S: 235 Authentication succeeded
[smtp:1] C: MAIL FROM:<x@domain.com> SIZE=6
[smtp:1] C: RCPT TO:<y@gmail.com>
[smtp:1] C: DATA
[smtp:1] S: 250 OK
[smtp:1] S: 250 Accepted
[smtp:1] S: 354 Enter message, ending with "." on a line by itself
[smtp:1] C: {...6 bytes of data...}
[smtp:1] C: .
[smtp:1] S: 550-Your FROM address ( x@domain.com ,  ) must match your authenticated
[smtp:1] S: 550 email user ( x@domain.com ).
[smtp:1] C: QUIT
[smtp:1] C: Disconnecting`

**Comment by ADoncel** [comment]
I finally solve the problem, it was because of:
```
std::ostringstream data;
data << "TEST" << "\r\n";

vmime::string msgData = data.str();
vmime::utility::inputStreamStringAdapter vis(msgData);

tr->send(from, to, vis, msgData.length());
```
As your example 6 was saying, doesn't work for me. If I want to do this I also need to add **From** value at the beginning of data:
```
std::ostringstream data;
data << "From: x@domain.com" << "\r\n";
data << "TEST" << "\r\n";
```
Or go by the other way:
```
vmime::messageBuilder mb;
mb.setExpeditor(from);
mb.setRecipients(to);
mb.setSubject(vmime::text("VMIME test mail"));

vmime::shared_ptr <vmime::message> msg = mb.construct();
tr->send(msg);
```
So, I think your method:
```
virtual void send(
		const mailbox& expeditor,
		const mailboxList& recipients,
		utility::inputStream& is,
		const size_t size,
		utility::progressListener* progress = NULL,
		const mailbox& sender = mailbox()
	) = 0;
```
It's not really working as it should, or maybe not and it was my computer, anyway I hope to help someone else that may have the same problem.

**Comment by vincent-richard** [comment]
That's not a bug in VMime, that's because "message data" (either the text you enter in example6 or the content of the input stream) always mean the whole message (header + body), not only the body.

When you use send(msg) instead, it will send the header automatically.

It seems your SMTP server expects the "From: " header to match the "From" in the envelope (which is sent with the "MAIL FROM:" SMTP command).
