### ISSUE TITLE
Invalid Server Response (IMAP) when trying to receiving a LIST from virginmedia.com

### ISSUE THREAD

**Issue by toxicated101** [kisli/vmime#250]
A response from a LIST command to imap.virginmedia.com returns

`* LIST (\HasNoChildren \UnMarked) "/" [Gmail]/Starred` 

Which cause the asting parseImpl to call VIMAP_PARSER_GET(atom, at); and return false, which causes the LIST cmd to fail.

It appears virginmedia uses gmail however when google returns the same string is is encapsulated in quotes

`* LIST (\HasNoChildren \UnMarked) "/" "[Gmail]/Starred"`

Virginmedia does put quotes around folder names with spaces and these do not fail.
`* LIST (\HasNoChildren \UnMarked) "/" "[Gmail]/Sent Items"`

It appears that the parser isn't expecting [ in the folder name that isn't quoted.

**Comment by vincent-richard** [comment]
This patch should fix the problem.
But please note that it will only work in "non-strict" mode, as this is non-standard IMAP.
