### ISSUE TITLE
AOL OK SEARCH complete only appearing after another command after SEARCH FAILS

### ISSUE THREAD

**Issue by toxicated101** [kisli/vmime#261]
Sending the SEARCH command returns a result but the OK SEARCH COMPLETE doesn't show up in the trace until after I have issues another command first causing the SEARCH to fail.

Trace Output
[imaps:2] S: a004 OK ID completed
[imaps:2] C: a005 SELECT INBOX
[imaps:2] S: * 40 EXISTS
[imaps:2] S: * 0 RECENT
[imaps:2] S: * OK [UIDVALIDITY 1590997014] UIDs valid
[imaps:2] S: * OK [UIDNEXT 69] Predicted next UID
[imaps:2] S: * FLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded $Junk $NotJunk)
[imaps:2] S: * OK [PERMANENTFLAGS (\Answered \Deleted \Draft \Flagged \Seen $Forwarded $Junk $NotJunk)] Permanent flags
[imaps:2] S: * OK [HIGHESTMODSEQ 127]
[imaps:2] S: * OK [MAILBOXID (1)] Ok
[imaps:2] S: a005 OK [READ-WRITE] SELECT completed; now in selected state
[imaps:2] C: a006 SEARCH OR TEXT "joan" OR SUBJECT "joan" FROM "joan"
[imaps:2] S: * SEARCH 35
[imaps:2] C: a007 STATUS INBOX (MESSAGES UNSEEN UIDNEXT UIDVALIDITY)
[imaps:2] S: a006 OK SEARCH completed

[AOLParserOutput.txt](https://github.com/kisli/vmime/files/6441999/AOLParserOutput.txt)

**Comment by toxicated101** [comment]
The only difference I can see from a valid call to an invalid call 

"* SEARCH 3 4 5 6 12 13 14 15 16 19 20 21 24 25 26 27 28 29 30 32 35 36 37 38 39 40 \r\n" AOL
"* SEARCH 1 2 3 4 5 7 17 21 22 25 26 27 28 29 30 34 35 40 41 42 43 44 49 50 51 55 67 68 69 70 71 73 74 75 76 80 81 82 83 84 85 86 87\r\n"  BT

The AOL one that doesn't work appears to have a space between the \r\n.

**Comment by vincent-richard** [comment]
Hello! Thank you for the report, I will provide a workaround for this within a few days.

**Comment by vincent-richard** [comment]
Could you please try the following patch and confirm the issue is fixed?
https://www.vmime.org/public/download/patches/vmime-20210510-aol-imap-search-workaround.patch
