### ISSUE TITLE
Trying to connect to a hotmail / live  SMTP server causes "Information cannot be provided" exception

### ISSUE THREAD

**Issue by toxicated101** [kisli/vmime#265]
Trying to connect to a live / hotmail / smtp.office365.com server  using
Port: 587
Security: TLS
Server: smtp.office365.com 

causes a authentication_exception("Information cannot be provided.", other).

Function: Smtp::Test, Exception [Information cannot be provided.]
Connection Trace:
=================
[smtp:1] C: Connecting to smtp-mail.outlook.com, port 587
[smtp:1] S: 220 LO4P123CA0220.outlook.office365.com Microsoft ESMTP MAIL Service ready at Fri, 23 Jul 2021 13:05:12 +0000
[smtp:1] C: EHLO ****************
[smtp:1] S: 250-LO4P123CA0220.outlook.office365.com Hello [195.171.72.163]
[smtp:1] S: 250-SIZE 157286400
[smtp:1] S: 250-PIPELINING
[smtp:1] S: 250-DSN
[smtp:1] S: 250-ENHANCEDSTATUSCODES
[smtp:1] S: 250-STARTTLS
[smtp:1] S: 250-8BITMIME
[smtp:1] S: 250-BINARYMIME
[smtp:1] S: 250-CHUNKING
[smtp:1] S: 250 SMTPUTF8
[smtp:1] C: STARTTLS
[smtp:1] S: 220 2.0.0 SMTP server ready
[smtp:1] C: Beginning SSL/TLS handshake
[smtp:1] C: Getting peer certificates
[smtp:1] C: EHLO **********************
[smtp:1] S: 250-LO4P123CA0220.outlook.office365.com Hello [195.171.72.163]
[smtp:1] S: 250-SIZE 157286400
[smtp:1] S: 250-PIPELINING
[smtp:1] S: 250-DSN
[smtp:1] S: 250-ENHANCEDSTATUSCODES
[smtp:1] S: 250-AUTH LOGIN XOAUTH2
[smtp:1] S: 250-8BITMIME
[smtp:1] S: 250-BINARYMIME
[smtp:1] S: 250-CHUNKING
[smtp:1] S: 250 SMTPUTF8
[smtp:1] C: Disconnecting

![Exception](https://user-images.githubusercontent.com/28094180/126789274-302d443f-7521-462f-9d78-a1e31d6e0ee0.png)

**Comment by vincent-richard** [comment]
Hello! Is this actually an issue?

**Comment by toxicated101** [comment]
No , sorry it was some code in my end that was changing the order of the AUTH list, I added it to get Yahoo to send email via oAuth2. I closed the issue a soon as I realised.
