### ISSUE TITLE
base64 encoding split up (in wrongly padded) parts..

### ISSUE THREAD

**Issue by srepmub** [kisli/vmime#98]
problem encountered with zarafa. apparently gmail, exchange are able to handle this kind of insanity at least:

    vmime::string inData = "Subject: =?utf-8?B?5Lit5?=\n =?utf-8?B?paH?=";
    vmime::text outText;
    vmime::text::decodeAndUnfold(inData, &outText);
    vmime::string result = outText.getConvertedText(vmime::charset("utf-8"));
    printf("Result: %s\n", result.c_str());

**Comment by vincent-richard** [comment]
Fixed! Thanks for reporting this.

**Comment by srepmub** [comment]
thanks a lot for fixing this quickly!!
