### ISSUE TITLE
Commit "Fixed auto_ptr<> not to be used with new[]" for charsetConverter_icu.cpp

### ISSUE THREAD

**Issue by wizball73** [kisli/vmime#99]
In commit 96f6d2389f322bddda00deae64bbcfaf5bde522d the use of std::auto_ptr<> and new for allocating buffer space for conversions is removed in favour of dynamic stack arrays (VLAs). Unfortunately, MSVC does not support C99, and according to their development information most likely never will, so this particular change does not compile under VS.

In my local tree I changed this to allocate space using a std::vector<> instead.

Regards,
Joel Hortelius

**Comment by vincent-richard** [comment]
Fixed, thanks!
